# AEQUIFY - codename:gematria

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  
services:
  aequify:
    image: eins0fx/aequify:gematria-0.33.666.3
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    volumes:
      - ./user_data:/app/user_data
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "if [ $$(( $$(date +%s) - $$(stat -c %Y /proc/1) )) -gt 14400 ]; then exit 1; else exit 0; fi"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
