# AEQUIFY - codename:gematria

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  
services:
  aequify:
    image: eins0fx/aequify:gematria-0.33.666.3
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    volumes:
      - ./user_data:/app/user_data
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
