services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  aequify:
    image: eins0fx/aequify:stable-0.69.0.420
    environment:
      LOG_LEVEL: debug
      REDIS_URL: redis://redis:6379
    volumes:
          - ./logs:/app/logs
          - ./user_data:/app/user_data
    command: [ "serve", "--env", "production" ]
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data: